version: "0.1"
services :
  sesac-torch:
    image : chosuna114/sesac-jenkins-test
    ports : 
      - 5001:5000
    volumes : 
      - /home/chosuna114/jenkins:/home
    environment:
      - STAGE = DEV

